### PR TITLE
WF-2088 :  php sdk update

### PR DESCRIPTION
**Pull request by preetishishodia7**
[WF-2088](https://mailinblue.atlassian.net/browse/WF-2088)

- Allow country code when the phone number is passed
- You can now enter an unsubscription page id to change the default unsubscription page.
- Added update form id.
- Changed default limit to 2500 and maximum limit to 5000 to /smtp/statistics/events
- Limit decreases to 50 from 500 for the default result returned for Email campaigns
- Set minimum value of all integer fields to 0
- The segment_ids is mandatory if list ids are not used.
- The isRecurring boolean field is added to create contact attributes endpoint

### CODE REVIEW

**Comment by deguif** [comment]
@preetishishodia7 this one should probably be merged: https://github.com/sendinblue/APIv3-php-library/pull/124
It would avoid errors on CI you encountered previously as packages versions can vary depending on which PHP version is installed.

**Review by shubhamUpadhyayInBlue — APPROVED** [review]
LGTM

**Comment by deguif** [comment]
Thanks @preetishishodia7

**Comment by stkrelax** [comment]
This Merge causes


Class SendinBlue\Client\Model\CreateUpdateProduct located in ./vendor/sendinblue/api-v3-sdk/lib/Model/CreateUpdateproduct.php does not comply with psr-4 autoloading standard. Skipping.
Class SendinBlue\Client\Model\FileList located in ./vendor/sendinblue/api-v3-sdk/lib/Model/FIleList.php does not comply with psr-4 autoloading standard. Skipping.
Class SendinBlue\Client\Model\ConversationsMessageFileImageInfo located in ./vendor/sendinblue/api-v3-sdk/lib/Model/ConversationsMessageFIleImageInfo.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by stkrelax** [comment]
ConversationsMessageFIleImageInfo has capital letter I in filename
CreateUpdateproduct needs capital P in filename 
FIleList has capital letter I in Filename

**Comment by preetishishodia7** [comment]
Hi @stkrelax Thanks for commenting, I'll update it asap.

**Pull request merged**
