### PR TITLE
Rename files SMS -> Sms

### LINKED ISSUE #113: RequestSmsRecipientExport PSR-4 issue
Deprecation Notice: Class SendinBlue\Client\Model\RequestSmsRecipientExport located in /vendor/sendinblue/api-v3-sdk/lib/Model/RequestSMSRecipientExport.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0.

File name should match class name. SMS != Sms

### PR DESCRIPTION
**Pull request by mvdnbrk**
Resolves #113

### CODE REVIEW

**Review by pcomble — APPROVED** [review]

**Comment by abishekrsrikaanth** [comment]
any change this can be merged in? Have been waiting for this as this is currently a show stopper with this library for projects using composer 2

**Comment by deguif** [comment]
Can we move forward this one, now that composer v2 got released.

**Comment by mvdnbrk** [comment]
Opened a support ticket with Send in Blue about this PR

**Comment by rajatsib** [comment]
Hi @mvdnbrk 

We will review this PR and update on it soon

**Comment by mvdnbrk** [comment]
@rajatsib Thanks!

**Comment by rajatsib** [comment]
Hi @mvdnbrk 

Thank you for your suggestions. We have merged your PR.

Regards
Sendinblue Team

**Pull request merged**
