### PR TITLE
Allow guzzle v7

### PR DESCRIPTION
**Pull request by gmponos**
Hi,

We have recently tagged a new version 7 of guzzle.

https://github.com/guzzle/guzzle/releases/tag/7.0.0

🎉

### CODE REVIEW

**Comment by r0073rr0r** [comment]
Please allow Guzzle 7

**Comment by mvdnbrk** [comment]
@rajatsib @ekta-slit @shubhamUpadhyayInBlue 

Can we merge this in?

**Comment by bobbybouwmann** [comment]
@rajatsib Can we get this merged? It's blocking us from updating to Laravel 8 because that requires Guzzle 7.

**Comment by rajatsib** [comment]
Hello @gmponos
Thank you for contacting us.
We appreciate your suggestions and have merged the PR.
Regards
SendinBlue Team

**Pull request merged**
